# Generated by Django 4.2.18 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Web', 'Web'), ('Crypto', 'Crypto'), ('Forensics', 'Forensics'), ('Pwn', 'Pwn'), ('Misc', 'Misc')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('flag', models.CharField(max_length=200)),
            ],
        ),
    ]
