# Generated by Django 4.2.18 on 2025-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Crypto', 'Crypto'), ('Forensics', 'Forensics'), ('Pwn', 'Pwn'), ('Misc', 'Misc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
