# Generated by Django 4.2.18 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved',
            field=models.ManyToManyField(blank=True, to='challenges.challenge'),
        ),
    ]
