# Generated by Django 4.2.18 on 2025-08-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('min_score', models.IntegerField()),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
