# Generated by Django 4.2.18 on 2025-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_category_alter_challenge_title'),
        ('users', '0003_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='challenges.challenge'),
        ),
    ]
